package Model.NetworkCommunication.Message;


public enum MessageType {

    SIGN_IN,
    SIGN_UP,
    LOG_OUT,
    PACK_MESSAGE,
    BAG_ITEM_MESSAGE,
    CHOOSE_BAG_MESSAGE,
    SHOP_MESSAGE,
    CHAT_MESSAGE,
    FRIEND_REQUEST,
    GAME_REQUEST,
    GAME_REQUEST_ANSWER,
    NEW_ITEM_MESSAGE,
    NEW_LOBBY_MESSAGE,
    NEW_LOBBY_MEMBER,
    REMOVE_LOBBY_MEMBER,
    ADD_ADMIN_MESSAGE,
    REMOVE_ADMIN_MESSAGE,

}
