package Model.NetworkCommunication.Message;


public enum MessageType {

    INIT_MESSAGE,
    SIGN_IN,
    SIGN_UP,
    LOG_OUT,
    PACK_MESSAGE,
    BAG_ITEM_MESSAGE,
    CHOOSE_BAG_MESSAGE,
    ONLINE_SHOP_MESSAGE,
    UPDATE_SHOP_MESSAGE,
    CHAT_MESSAGE,
    BLOCK_MESSAGE,
    FRIEND_REQUEST,
    FRIEND_REQUEST_ANSWER,
    GAME_REQUEST,
    GAME_REQUEST_ANSWER,
    NEW_LOBBY_MESSAGE,
    REMOVE_LOBBY_MESSAGE,
    JOIN_LOBBY_MESSAGE,
    LOBBY_CHAT_MESSAGE,
    NEW_LOBBY_MEMBER,
    REMOVE_LOBBY_MEMBER,
    ADD_ADMIN_MESSAGE,
    REMOVE_ADMIN_MESSAGE,

}
